# Default Project Configuration

set(DEFAULT_BASE_MESH_FILE mesh/mesh-square)
set(DEFAULT_MESH_SIZE 0.1)
set(DEFAULT_MODEL "TNNP")
set(DEFAULT_DELTA_T 0.005)
set(DEFAULT_MAX_TIME 60000)
set(DEFAULT_THETA 0.5)
set(DEFAULT_MAX_ITER 10000)
set(DEFAULT_TOLERANCE 1.0e-16)
set(DEFAULT_REDUCE_FACTOR 1.0e-6)
set(DEFAULT_SOLVER gmres)
set(DEFAULT_PRECONDITIONER ssor)
set(DEFAULT_ILU_FILL_IN 3)
set(DEFAULT_SSOR_OMEGA 1.0)

# Derived variables
set(MESH_COMPILING_COMMAND gmsh ${DEFAULT_BASE_MESH_FILE}.geo -save)
get_filename_component(MESH_STEM ${DEFAULT_BASE_MESH_FILE} NAME_WE)
set(DEFAULT_OUTPUT_FILE "output_ActivationTime-${MESH_STEM}")
